/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import MySQL_conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class Login_screen extends javax.swing.JFrame {

    conexion cc = new conexion();
    Connection con = cc.conexion();
    Statement st;
    ResultSet rs;
    
    public Login_screen() {
        initComponents();
        transparentButton();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButtonLoginButton = new javax.swing.JButton();
        jButtonSingup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EXIT_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TXTuserName = new javax.swing.JTextField();
        TXTpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Downloads\\Screenshot 2021-11-28 013550-PhotoRoom.png")); // NOI18N
        jLabel5.setText("jLabel5");

        jButtonLoginButton.setBackground(new java.awt.Color(0, 153, 255));
        jButtonLoginButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jButtonLoginButton.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLoginButton.setText("Iniciar sesion");
        jButtonLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginButtonActionPerformed(evt);
            }
        });

        jButtonSingup.setBackground(new java.awt.Color(0, 153, 255));
        jButtonSingup.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jButtonSingup.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSingup.setText("Registrarse");
        jButtonSingup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSingupActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel1.setText("Iniciar sesion");

        EXIT_button.setBackground(new java.awt.Color(255, 255, 255));
        EXIT_button.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        EXIT_button.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        EXIT_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cristian\\Desktop\\imagene\\close (2).png")); // NOI18N
        EXIT_button.setBorderPainted(false);
        EXIT_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");

        TXTuserName.setBackground(new java.awt.Color(175, 177, 179));
        TXTuserName.setBorder(null);

        TXTpassword.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        TXTpassword.setBorder(null);
        TXTpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTpasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña");

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EXIT_button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(TXTuserName)
                        .addComponent(TXTpassword)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSingup, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(EXIT_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSingup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginButtonActionPerformed
        login();
    }//GEN-LAST:event_jButtonLoginButtonActionPerformed

    private void EXIT_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT_buttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXIT_buttonActionPerformed

    private void TXTpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpasswordActionPerformed

    private void jButtonSingupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSingupActionPerformed
        Singup_screen singUp = new Singup_screen();
        singUp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSingupActionPerformed

    /**
     * @param args the command line arguments
     */
    public void transparentButton() {
        EXIT_button.setOpaque(false);
        EXIT_button.setContentAreaFilled(false);
        EXIT_button.setBorderPainted(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_screen().setVisible(true);
            }
        });
    }
    
    void login(){
        String password = String.valueOf(TXTpassword.getPassword());
        String usuario = TXTuserName.getText();
        String sql = "select * from usuarios where Nombre_usuario ='"+usuario+"' and Contraseña='"+password+"' ";
        try{
            st = con.createStatement();
            rs = st.executeQuery(sql);
            if(rs.next()) {
            JOptionPane.showMessageDialog(null,"Sesion iniciada con ezito");
            Tabla login = new Tabla();
            login.setVisible(true);
            this.setVisible(false);
            } else {JOptionPane.showMessageDialog(null,"El usuario no esta registrado o la Contraseña esta mal");}
        } catch (SQLException e) {JOptionPane.showMessageDialog(null,"Error al iniciar sesion");}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT_button;
    private javax.swing.JPasswordField TXTpassword;
    private javax.swing.JTextField TXTuserName;
    private javax.swing.JButton jButtonLoginButton;
    private javax.swing.JButton jButtonSingup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
